---
name: collect-ci-metrics
"on":
  workflow_run:
    workflows: ["🚀 Turbo CI - ice-t Persistent Runners"]
    types: [completed]

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: 📈 Capture CI metrics
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
          GH_FIELDS: >-
            conclusion,actor,headSha,createdAt,startedAt,updatedAt
        run: |
          set -euo pipefail
          mkdir -p .codex/metrics
          gh run view ${{ github.event.workflow_run.id }} \
            --json "$GH_FIELDS" \
            --jq '{
              run_id:     '"${{ github.event.workflow_run.id }}"',
              conclusion: .conclusion,
              run_duration_ms: (
                ((.updatedAt|fromdateiso8601) - (.startedAt|fromdateiso8601))
                * 1000
              ),
              queued_ms: (
                ((.startedAt|fromdateiso8601) - (.createdAt|fromdateiso8601))
                * 1000
              ),
              actor: .actor.login,
              head_sha: .headSha,
              created_at: .createdAt,
              started_at: .startedAt,
              finished_at: .updatedAt
            }' >> .codex/metrics/ci-metrics.jsonl

      - name: 📤 Commit metrics
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "ice-t-bot"
          git config user.email "ice-t-bot@users.noreply.github.com"
          git add -f .codex/metrics/ci-metrics.jsonl
          git commit --no-verify -m \
            "ci(metrics): append run ${{ github.event.workflow_run.id }}"
          git push
