---
name: collect-ci-metrics
"on":
  workflow_run:
    workflows: ["🚀 Turbo CI - ice-t Persistent Runners"]
    types: [completed]

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: 📈 Append CI metrics
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p .codex/metrics
          jq -n \
            --argjson run_id ${{ github.event.workflow_run.id }} \
            --arg branch "${{ github.event.workflow_run.head_branch }}" \
            --arg status "${{ github.event.workflow_run.conclusion }}" \
            --arg created_at "${{ github.event.workflow_run.created_at }}" \
            --arg started_at "${{ github.event.workflow_run.run_started_at }}" \
            --arg updated_at "${{ github.event.workflow_run.updated_at }}" \
            '{
              run_id: $run_id,
              branch: $branch,
              status: $status,
              created_at: $created_at,
              started_at: $started_at,
              updated_at: $updated_at,
              duration_ms: ( ( ($updated_at | fromdateiso8601) - ($started_at | fromdateiso8601) ) * 1000 ),
              queued_ms: ( ( ($started_at | fromdateiso8601) - ($created_at | fromdateiso8601) ) * 1000 )
            }' \
          >> .codex/metrics/ci-metrics.jsonl

      - name: 📤 Commit metrics
        shell: bash
        run: |
          set -euo pipefail
          git config user.name  "ice-t-bot"
          git config user.email "ice-t-bot@users.noreply.github.com"
          git add -f .codex/metrics/ci-metrics.jsonl
          git commit --no-verify -m "ci(metrics): append run ${{ github.event.workflow_run.id }} for ${{ github.event.workflow_run.head_branch }}"
          git push
