---
name: Test Simple CI for Logging
"on":
  push:
    paths:
      - "test-trigger-*"
  workflow_dispatch: {}

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test that will fail
        run: |
          echo "This job will fail to test logging"
          if [ -f "test-trigger-fail" ]; then
            echo "Triggering failure for log testing"
            exit 1
          fi
          echo "Job completed successfully" 